# Form implementation generated from reading ui file 'd:\Codding\RAL palette\form_1.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RAL_widget(object):
    def setupUi(self, RAL_widget):
        RAL_widget.setObjectName("RAL_widget")
        RAL_widget.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RAL_widget.sizePolicy().hasHeightForWidth())
        RAL_widget.setSizePolicy(sizePolicy)
        RAL_widget.setMinimumSize(QtCore.QSize(0, 0))
        RAL_widget.setMaximumSize(QtCore.QSize(800, 600))
        self.horizontalLayout = QtWidgets.QHBoxLayout(RAL_widget)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RAL_tab = QtWidgets.QTabWidget(parent=RAL_widget)
        self.RAL_tab.setObjectName("RAL_tab")
        self.Classic_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Classic_tab.sizePolicy().hasHeightForWidth())
        self.Classic_tab.setSizePolicy(sizePolicy)
        self.Classic_tab.setObjectName("Classic_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.Classic_tab)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.RAL_tab.addTab(self.Classic_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.RAL_tab.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.RAL_tab)

        self.retranslateUi(RAL_widget)
        self.RAL_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RAL_widget)

    def retranslateUi(self, RAL_widget):
        _translate = QtCore.QCoreApplication.translate
        RAL_widget.setWindowTitle(_translate("RAL_widget", "RAL Pallete"))
        self.RAL_tab.setTabText(self.RAL_tab.indexOf(self.Classic_tab), _translate("RAL_widget", "Classic"))
        self.RAL_tab.setTabText(self.RAL_tab.indexOf(self.tab_2), _translate("RAL_widget", "Tab 2"))
