# Form implementation generated from reading ui file 'd:\Codding\RAL palette\form.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RAL_widget(object):
    def setupUi(self, RAL_widget):
        RAL_widget.setObjectName("RAL_widget")
        RAL_widget.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(RAL_widget.sizePolicy().hasHeightForWidth())
        RAL_widget.setSizePolicy(sizePolicy)
        RAL_widget.setMinimumSize(QtCore.QSize(0, 0))
        RAL_widget.setMaximumSize(QtCore.QSize(800, 600))
        self.horizontalLayout = QtWidgets.QHBoxLayout(RAL_widget)
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RAL_tab = QtWidgets.QTabWidget(parent=RAL_widget)
        self.RAL_tab.setObjectName("RAL_tab")
        self.Classic_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Classic_tab.sizePolicy().hasHeightForWidth())
        self.Classic_tab.setSizePolicy(sizePolicy)
        self.Classic_tab.setObjectName("Classic_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Classic_tab)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.classic_tab_scroll_area = QtWidgets.QScrollArea(parent=self.Classic_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classic_tab_scroll_area.sizePolicy().hasHeightForWidth())
        self.classic_tab_scroll_area.setSizePolicy(sizePolicy)
        self.classic_tab_scroll_area.setAutoFillBackground(False)
        self.classic_tab_scroll_area.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.classic_tab_scroll_area.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.classic_tab_scroll_area.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.classic_tab_scroll_area.setWidgetResizable(True)
        self.classic_tab_scroll_area.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.classic_tab_scroll_area.setObjectName("classic_tab_scroll_area")
        self.classic_scroll_widget = QtWidgets.QWidget()
        self.classic_scroll_widget.setGeometry(QtCore.QRect(0, 0, 785, 556))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.classic_scroll_widget.sizePolicy().hasHeightForWidth())
        self.classic_scroll_widget.setSizePolicy(sizePolicy)
        self.classic_scroll_widget.setObjectName("classic_scroll_widget")
        self.classic_grid = QtWidgets.QGridLayout(self.classic_scroll_widget)
        self.classic_grid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.classic_grid.setObjectName("classic_grid")
        self.classic_tab_scroll_area.setWidget(self.classic_scroll_widget)
        self.verticalLayout.addWidget(self.classic_tab_scroll_area)
        self.RAL_tab.addTab(self.Classic_tab, "")
        self.horizontalLayout.addWidget(self.RAL_tab)

        self.retranslateUi(RAL_widget)
        self.RAL_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RAL_widget)

    def retranslateUi(self, RAL_widget):
        _translate = QtCore.QCoreApplication.translate
        RAL_widget.setWindowTitle(_translate("RAL_widget", "RAL Pallete"))
        self.RAL_tab.setTabText(self.RAL_tab.indexOf(self.Classic_tab), _translate("RAL_widget", "Classic"))
